export const CHANGE_SLIDER_TRANSFORM = 'CHANGE_SLIDER_TRANSFORM'
export const RESET_VALUE_TRANSFORM = 'RESET_VALUE_TRANSFORM'
export const ON_CHANGE_COLOR_TRANSFORM = 'ON_CHANGE_COLOR_TRANSFORM'

export const TRANSFORM = {
	ON_CHANGE_SLIDER: 'ON_CHANGE_SLIDER_TRANSFORM',
	ON_RESET_VALUE: 'ON_RESET_VALUE_TRANSFORM',
	ON_CHANGE_BG_COLOR: 'ON_CHANGE_BG_COLOR_TRANSFORM',
}

export const BOX_SHADOW = {
	ON_CHANGE_SLIDER: 'ON_CHANGE_SLIDER_BOX_SHADOW',
	ON_CHANGE_INSET: 'ON_CHANGE_INSET_BOX_SHADOW',
	ON_CHANGE_SHADOW_COLOR: 'ON_CHANGE_SHADOW_COLOR_BOX_SHADOW',
	ON_ADD_LAYER: 'ON_ADD_LAYER_BOX_SHADOW',
	ON_SWAP_LAYER: 'ON_SWAP_LAYER_BOX_SHADOW',
	ON_DELETE_LAYER: 'ON_DELETE_LAYER_BOX_SHADOW',
	ON_CLICK_LAYER: 'ON_CLICK_LAYER_BOX_SHADOW',
	ON_CHANGE_BG_COLOR: 'ON_CHANGE_BG_COLOR_BOX_SHADOW',
}
